name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build images
        run: docker-compose -f docker-compose.yml build
      - uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0
      - name: Deploy manifests
        run: kubectl apply -f k8s/
